deploy:
  image:  python:3.8-slim
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 rm s3://jameshopkins.ie --recursive
    - aws s3 sync ./ s3://james-hopkins-portfolio --acl public-read
